# Generated by Django 6.0.3 on 2026-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
